exp_name: 'C-B-D_3'

system:
  gpus: 1
  workers: 4
  batch_size: 32
  path: '/mnt/fast/nobackup/users/ts00987/vol/research/deep_localisation/challenge/'
  results_path: '/mnt/fast/nobackup/users/ts00987/vol/research/deep_localisation/challenge/results/'
  tune:
    batch_size: True


data:
  root: '/mnt/fast/nobackup/scratch4weeks/ts00987/datasets/University/'
  query_file: "src/data/query_street_name.txt"
  use_drone: True
  use_google: False

model:
  shared_extractor: False
  backbone: 'convnext'
  size: 'base'
  image_size: 384
  epochs: 500
  lr: 1e-4
  drone_weight: 1.0


