exp_name: 'ts_local'

system:
  gpus: 1
  workers: 0
  batch_size: 4
  scheduler: 'cos'
  path: '/vol/research/deep_localisation/challenge/'
  results_path: '/vol/research/deep_localisation/challenge/results/'
  tune:
    batch_size: True

data:
  root: '/scratch/datasets/University/'
  query_file: "src/data/query_street_name.txt"

model:
  shared_extractor: False
  backbone: 'convnext'
  size: 'tiny'
  image_size: 384
  epochs: 10
  lr: 1e-4



