exp_name: 'hpc'

system:
  gpus: 1
  workers: 0
  batch_size: 32
  scheduler: 'cos'
  path: '/mnt/fast/nobackup/users/ts00987/vol/research/deep_localisation/challenge/'
  results_path: '/mnt/fast/nobackup/users/ts00987/vol/research/deep_localisation/challenge/results/'
  tune:
    batch_size: True


data:
  root: '/mnt/fast/nobackup/scratch4weeks/ts00987/datasets/University/'
  query_file: "src/data/query_street_name.txt"
  type: 'folder'

model:
  shared_extractor: False
  backbone: 'vit'
  size: 'huge'
  image_size: 336
  epochs: 300
  lr: 1e-4


