exp_name: 'tiny'
system:
  gpus: 1
  workers: 4
  batch_size: 64

data:
  root: '/home/shitbox/datasets/University-Release/'
  sample_equal: True

model:
  backbone: 'vit'
  size: 'small'
  image_size: 384

  epochs: 200
  shared_extractor: False
  head: 
    use: False
    params:
      inter_dims: 768
      hidden_dims: 768
      output_dims: 768


